# Generated by Django 3.2.6 on 2021-08-11 02:03

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.FloatField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(-34)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MaxValueValidator(-7), django.core.validators.MinValueValidator(-74)])),
                ('ponto', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('evento', models.CharField(choices=[('CHV', 'Chuva Excessica'), ('GEA', 'Geada'), ('GRA', 'Granizo'), ('SEC', 'Seca'), ('VEN', 'Vendaval'), ('RAI', 'Raio')], max_length=3)),
                ('datacolheita', models.DateField()),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proagro.cultura')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
