#  Copyright (c) 2021.
#  Julio Cezar Riffel<julioriffel@gmail.com>

# Generated by Django 3.2.6 on 2021-08-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('proagro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultura',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome cultura'),
        ),
    ]
